### PR TITLE
SLING-7932 - Use Regex to parse mvn GAVs and URLs

### PR DESCRIPTION
**Pull request by simonetripodi**
initial checkin

### CODE REVIEW

**Comment by bosschaert** [comment]
Hi @simonetripodi I like the unit tests in this pull request, but I'm wondering about the code changes. I'm not entirely sure the regex are that much better/easier than what was there before. And they are most likely not faster.
I would be inclined to take just the tests from this pull request (assuming they work with the current code) and leave the actual code changes the way they are...

**Comment by bdelacretaz** [comment]
+1 to what @bosschaert says - if the original parser works, don't fix it ;-)

Note that our parent pom includes a Jacoco setup to quickly check test coverage, build with `-P jacoco-report` and see the `target/site/jacoco-merged/index.html` report. Before these changes the report indeed shows some code paths which are not tested in `ArtifactId#fromMvnUrl`

**Comment by simonetripodi** [comment]
Hi there @bosschaert , thanks for reviewing this old PR!

Is there any quick way you can take just the tests from the PR? Or I have to re-submit it? TIA!

**Comment by bosschaert** [comment]
Hi @simonetripodi yes, was able to merge just the tests - thanks!

**Comment by simonetripodi** [comment]
Cool! :)

As a side note, current parser implementation needs to be adjusted, while an input like

`group.a     :     artifact.b :  zip   :   foo  :    1.0`

would be rejected by the regexp, for the current parser it still looks as a valid input - and unit tests would fail

/CC @bdelacretaz

**Pull request merged**
