### PR TITLE
SLING-8998: Add feature-origins metadata entry to artifacts in featur…

### PR DESCRIPTION
**Pull request by karlpauls**
…es when merging

### CODE REVIEW

**Review by bosschaert — APPROVED** [review]
There is a test failure that looks small, but apart from that LGTM

**Review by cziegeler — COMMENTED** [review]
Lgtm, thanks - can we have a constant for the metadata key in Artifact and maybe a get method like getFeatureSources() returning an array of ArtifactIds (or an empty one)?

**Comment by karlpauls** [comment]
@bosschaert, fixed now - just fat-fingered it during the commit. 

@cziegeler, good idea, i'll add that and update this PR.

**Comment by karlpauls** [comment]
@cziegeler, PTAL again :-)

**Review by cziegeler — APPROVED** [review]
Thanks

**Pull request merged**
